/**
 * Unichat
 * - The Unichat application consists of an HTTP service functioning a central hub
 *  for multiple clients chatting by means of __chat rooms__
 *  + Chat rooms can be referenced by means of their name, which is assumed to be unique
 *  + The members of a chat room can see the whole sequence of messages published within that chat room or just a sub-sequence
 *  + The members of a chat room can see the whole set of members of the chat room
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package model
import play.api.libs.json._

case class MemberInChatRoom (
                  username: Option[String],
                  link: Option[String]
)

object MemberInChatRoom {
implicit val format: Format[MemberInChatRoom] = Json.format
}

